# Generated by Django 5.1 on 2024-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('health', models.IntegerField(default=100, verbose_name='Здоровье')),
                ('attack', models.IntegerField(default=10, verbose_name='Атака')),
                ('defense', models.IntegerField(default=0, verbose_name='Защита')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
            ],
            options={
                'verbose_name': 'Создание',
                'verbose_name_plural': 'Создания',
            },
        ),
    ]
