# Generated by Django 5.1 on 2024-08-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('attacker_attack_impact', models.IntegerField(default=0, verbose_name='Влияние на атаку атакующей стороны')),
                ('attacker_defense_impact', models.IntegerField(default=0, verbose_name='Влияние на защиту атакующей стороны')),
                ('defender_attack_impact', models.IntegerField(default=0, verbose_name='Влияние на атаку защищающейся стороны')),
                ('defender_defense_impact', models.IntegerField(default=0, verbose_name='Влияние на защиту защищающейся стороны')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
    ]
