version: '3.3'

volumes:
  pg_data_creatures:
  pg_data_humans:
  creatures_static:

networks:
  creatures_network:
  humans_network:

services:
  redis:
    container_name: redis-cvh
    image: redis:7.4-alpine
    networks: 
      - creatures_network
      - humans_network

  db_creatures:
    container_name: db_creatures-cvh
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_CREATURES_DB:-creatures}
      POSTGRES_USER: ${POSTGRES_CREATURES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_CREATURES_PASSWORD:-postgres}
      DB_HOST: ${DB_CREATURES_HOST:-db_creatures}
      DB_PORT: ${DB_CREATURES_PORT:-5432}
    volumes:
      - pg_data_creatures:/var/lib/postgresql/data
    networks:
      - creatures_network
  creatures:
    container_name: creatures-cvh
    build: ../creatures/
    env_file: .env
    volumes:
      - creatures_static:/creatures_static
    depends_on:
      - db_creatures
      - redis
    networks: 
      - creatures_network
  creatures_celery:
    container_name: creatures_celery-cvh
    build: ../creatures/
    env_file: .env
    command: celery -A creatures worker -Q creatures -l info
    depends_on:
      - creatures
    networks: 
      - creatures_network

  db_humans:
    container_name: db_humans-cvh
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_HUMANS_NAME:-humans}
      POSTGRES_USER: ${DB_HUMANS_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_HUMANS_PASSWORD:-postgres}
      DB_HOST: ${DB_HUMANS_HOST:-db_humans}
      DB_PORT: ${DB_HUMANS_PORT:-5432}
    volumes:
      - pg_data_humans:/var/lib/postgresql/data
    networks:
      - humans_network
  humans:
    container_name: humans-cvh
    build: ../humans/
    env_file: .env
    depends_on:
      - db_humans
      - redis
    networks: 
      - humans_network
  humans_celery:
    container_name: humans_celery-cvh
    build: ../humans/
    env_file: .env
    command: celery -A celery_app.celery_app worker -Q humans -l info
    depends_on:
      - humans
    networks: 
      - humans_network

  gateway:
    container_name: gateway-cvh
    image: nginx:1.25.4-alpine
    depends_on:
      - humans_celery
      - creatures_celery
    ports:
      - 80:80
      - 81:81
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - creatures_static:/usr/share/nginx/html/
    networks: 
      - creatures_network
      - humans_network
