# Generated by Django 5.1 on 2024-08-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('new_creature_birth_process', models.IntegerField(default=0, verbose_name='Процесс рождения нового существа')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nests', to='area.area', verbose_name='Территория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nests', to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
            ],
        ),
    ]
