"""Add group and units

Revision ID: b6ae182b56eb
Revises: 9e5a48fa4b47
Create Date: 2024-09-05 11:40:57.245760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ae182b56eb'
down_revision: Union[str, None] = '9e5a48fa4b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('headquarters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headquarters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('director_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('recruitment_process', sa.INTEGER(), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('director_id', 'name', name='director_id_name_unique_constraint')
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('attacker_attack_impact', sa.INTEGER(), nullable=True),
    sa.Column('attacker_defense_impact', sa.INTEGER(), nullable=True),
    sa.Column('defender_attack_impact', sa.INTEGER(), nullable=True),
    sa.Column('defender_defense_impact', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.BLOB(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
