"""empty message

Revision ID: f91d756bc5db
Revises: 79bbdb7d9398
Create Date: 2024-09-09 17:48:55.940190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91d756bc5db'
down_revision: Union[str, None] = '79bbdb7d9398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('headquarters')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('units')
    op.drop_table('groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('director_id', sa.INTEGER(), nullable=True),
    sa.Column('headquarter_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['headquarter_id'], ['headquarters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('director_id', 'name', name='director_id_group_name_unique_constraint')
    )
    op.create_table('units',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('director_id', sa.INTEGER(), nullable=True),
    sa.Column('expirience', sa.INTEGER(), nullable=True),
    sa.Column('health', sa.INTEGER(), nullable=True),
    sa.Column('attack', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('attacker_attack_impact', sa.INTEGER(), nullable=True),
    sa.Column('attacker_defense_impact', sa.INTEGER(), nullable=True),
    sa.Column('defender_attack_impact', sa.INTEGER(), nullable=True),
    sa.Column('defender_defense_impact', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.BLOB(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('headquarters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('director_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('recruitment_process', sa.INTEGER(), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('director_id', 'name', name='director_id_hq_name_unique_constraint')
    )
    # ### end Alembic commands ###
